import fs from "node:fs";
import path from "node:path";
import { recordTelemetry } from "./telemetry.mjs";

export const STAGES = [
  "welcome",
  "expectations",
  "stance",
  "first_story",
  "first_build",
  "first_ship",
  "next_steps",
];

const STATE_FILE = ".rks/onboarder-state.json";
const PROJECT_JSON = ".rks/project.json";

// ─── State helpers ────────────────────────────────────────────────────────────

export function getOnboarderState(projectRoot) {
  const statePath = path.join(projectRoot, STATE_FILE);
  if (!fs.existsSync(statePath)) {
    const now = Date.now();
    return {
      version: 1,
      startedAt: now,
      lastTouchedAt: now,
      completedStages: [],
      currentStage: "welcome",
      projectId: null,
    };
  }
  try {
    return JSON.parse(fs.readFileSync(statePath, "utf8"));
  } catch {
    const now = Date.now();
    return {
      version: 1,
      startedAt: now,
      lastTouchedAt: now,
      completedStages: [],
      currentStage: "welcome",
      projectId: null,
    };
  }
}

export function saveOnboarderState(projectRoot, state) {
  const statePath = path.join(projectRoot, STATE_FILE);
  const updated = { ...state, lastTouchedAt: Date.now() };
  fs.mkdirSync(path.dirname(statePath), { recursive: true });
  fs.writeFileSync(statePath, JSON.stringify(updated, null, 2), "utf8");
  return updated;
}

function readProjectJson(projectRoot) {
  const p = path.join(projectRoot, PROJECT_JSON);
  if (!fs.existsSync(p)) return {};
  try { return JSON.parse(fs.readFileSync(p, "utf8")); } catch { return {}; }
}

function writeProjectJson(projectRoot, data) {
  const p = path.join(projectRoot, PROJECT_JSON);
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, JSON.stringify(data, null, 2), "utf8");
}

// ─── File generation ──────────────────────────────────────────────────────────

export function generateProjectFiles(projectRoot, projectData = {}) {
  const notesDir = path.join(projectRoot, "notes");
  if (!fs.existsSync(notesDir)) {
    fs.mkdirSync(notesDir, { recursive: true });
  }

  const projectId = projectData.projectId || path.basename(projectRoot);
  const oneLiner = projectData.one_liner || `${projectId} — add a description here.`;
  const typeDesc = projectData.type_description || null;
  const timestamp = Date.now();

  const overviewPath = path.join(notesDir, "project.overview.md");
  const overviewExists = fs.existsSync(overviewPath);
  if (!overviewExists) {
    fs.writeFileSync(overviewPath, `---
id: project.overview
title: "Project Overview"
desc: "${oneLiner}"
created: ${timestamp}
updated: ${timestamp}
---

# ${projectId}

## About This Project

${oneLiner}
${typeDesc ? `\n${typeDesc}\n` : ""}`, "utf8");
  }

  const agentsPath = path.join(projectRoot, "AGENTS.md");
  const agentsExists = fs.existsSync(agentsPath);
  if (!agentsExists) {
    fs.writeFileSync(agentsPath, `# AGENTS.md

<!-- Generated by rks onboarder. Edit freely — this is your project's context file. -->

## About

${projectId} — ${oneLiner}

## Build & Test

\`\`\`bash
# Add your build and test commands here
\`\`\`

## Architecture

<!-- Describe your project's key directories and entry points -->

## Conventions

<!-- Add coding standards, naming conventions, or patterns specific to this project -->

## Git Workflow

Branch from \`staging\`. PR into \`staging\`. Squash merge.
Branch naming: \`feature/\`, \`fix/\`, \`refactor/\`, \`docs/\`, \`chore/\`
`, "utf8");
  }

  return { overviewCreated: !overviewExists, agentsCreated: !agentsExists };
}

// ─── Rate card and cost summary ──────────────────────────────────────────────

export const RATE_CARD = {
  "claude-opus-4-7":    { input: 15 / 1e6,    output: 75 / 1e6 },
  "claude-sonnet-4-6":  { input: 3 / 1e6,     output: 15 / 1e6 },
  // Haiku 4.5 is $1/$5 per 1M — NOT the old Haiku 3.5 $0.25/$1.25.
  "claude-haiku-4-5":   { input: 1 / 1e6,     output: 5 / 1e6 },
};

function buildCostSummary(buildData) {
  if (!buildData) return "not recorded";
  const { rawCost, inputTokens, outputTokens, modelName } = buildData;

  if (rawCost != null) {
    return `~$${rawCost.toFixed(4)} (Approximate; actual cost depends on your Anthropic plan)`;
  }

  const rate = modelName ? RATE_CARD[modelName] : null;
  if (inputTokens != null && rate) {
    const dollars = inputTokens * rate.input + (outputTokens || 0) * rate.output;
    return `~$${dollars.toFixed(4)} via ${modelName} (Approximate; actual cost depends on your Anthropic plan)`;
  }

  if (inputTokens != null) {
    const total = inputTokens + (outputTokens || 0);
    return `${total} tokens via ${modelName || "unknown model"} (rate card unavailable)`;
  }

  return "not recorded";
}

// ─── Telemetry helpers ────────────────────────────────────────────────────────

function emit(projectRoot, slug, metrics = {}) {
  try {
    recordTelemetry(projectRoot, { slug, metrics, timestamp: Date.now() });
  } catch {
    // telemetry is best-effort
  }
}

// ─── Stage handlers ───────────────────────────────────────────────────────────

function makePayload(stage, state, display = "", extra = {}) {
  return { ok: true, stage, display, prompts: [], nextAction: {}, state, ...extra };
}

function handleWelcome(state, opts, projectRoot) {
  const { bounce } = opts || {};
  const responses = opts?.responses || {};

  // Capture verbosityChoice if provided on this or prior call
  const verbosityChoice = responses.verbosityChoice;
  if (verbosityChoice !== undefined) {
    if (!state.responses) state.responses = {};
    state.responses.verbosityChoice = verbosityChoice;
    if (verbosityChoice === "yes") {
      state.sessionVerbose = true;
    }
  }

  if (bounce) {
    emit(projectRoot, "onboarder.stage.skipped", { stage: "welcome", reason: "bounced" });
    const proj = readProjectJson(projectRoot);
    proj.onboarder = { ...(proj.onboarder || {}), dismissed: true };
    writeProjectJson(projectRoot, proj);
    state.dismissed = true;
    return makePayload("welcome", state,
      "Thanks for trying rks. If you change your mind, `/rks-onboard --reset`. — UX287."
    );
  }

  const isFreshSession = !state.completedStages || state.completedStages.length === 0;
  if (isFreshSession) {
    emit(projectRoot, "onboarder.session.started", {
      projectId: state.projectId,
      version: state.version,
      source: "auto-trigger",
    });
  }

  emit(projectRoot, "onboarder.stage.started", { stage: "welcome" });
  const t0 = Date.now();

  // Verbosity detection
  const proj = readProjectJson(projectRoot);
  const verbosity = proj.verbosity || process.env.RKS_VERBOSITY || "verbose";
  const alreadyVerbose = verbosity === "verbose";
  const verbosityPrompt = alreadyVerbose
    ? ""
    : `\n\nOne note before we continue: your project verbosity is set to \`${verbosity}\`. Stages 4-6 are designed to show the Governor in action — tool calls, plans, and results live. Should we switch to verbose mode for this onboarding session? (Type **yes** to enable for this session, or **no** to continue as-is)`;

  const display = `Welcome. You're in routekit-shell — rks for short.

Here is what this is, in one paragraph:

rks is a hooked-agent framework: it runs your AI agent inside hook-enforced lanes, with a local knowledge graph, audit trail, and structured pipeline for every unit of work. Every change is either a **story** — a small piece of work with a defined scope and tests — or a **framework update** to rks itself. The agent doesn't freelance. It writes a plan, you see the plan, the plan is enforced as it runs, and every commit ships through a transparent pipeline.

The primary use case today is software development — governed AI-driven code changes with cost visibility and scope enforcement. The framework is general enough to apply anywhere you want governed agents, structured audit trails, and a local knowledge graph: research workflows, document automation, data pipelines.

If you've worked in any domain where an AI agent ran off-script and left a mess behind — rks is the response to that.

The next six stages take about ten minutes. We'll set expectations, walk through the permission model, and then write and ship a real first story together. By the end you'll have a PR open with a real cost report attached.

If that's not what you want — if you came looking for a freeform AI environment — this is the right moment to know that's not what rks is. Type \`/rks-onboard --bounce\` and we'll part ways cleanly.${verbosityPrompt}

Ready to continue? Type **yes** (or any response) to move to Stage 2, or \`/rks-onboard --bounce\` to exit.`;

  if (!state.completedStages.includes("welcome")) {
    state.completedStages.push("welcome");
  }
  generateProjectFiles(projectRoot, { projectId: state.projectId });

  emit(projectRoot, "onboarder.stage.completed", {
    stage: "welcome",
    durationSeconds: Math.round((Date.now() - t0) / 1000),
  });

  return makePayload("welcome", state, display);
}

function handleExpectations(state, opts, projectRoot) {
  emit(projectRoot, "onboarder.stage.started", { stage: "expectations" });
  const t0 = Date.now();

  const display = `Two things gate what the agent does. You should know about both before we start the first story.

**Layer one: Claude Code's user-approval prompts.** When the agent wants to call a tool — read a file, run a command, write a commit — Claude Code asks you. The first time you see a prompt for a given tool, you'll have three choices: allow once, allow always for this project, or deny. This is standard Claude Code behavior — rks does not bypass it.

Practical tip: in the first session you'll see a flurry of prompts as the agent reaches for tools the project hasn't approved yet. Most of them are safe to allow-always at the project level. The ones to think twice about are bash commands and writes to sensitive paths (\`.env\`, credentials). Claude Code shows you the exact command before you approve it.

**Layer two: rks's hook-enforced lanes.** Independent of Claude Code's prompts, rks installs PreToolUse hooks that check every Edit/Write/Bash call against the active scope. If a Governor is running a plan with \`targetFiles: [src/foo.js]\` and the agent tries to write \`src/bar.js\`, the hook blocks it. Claude Code says "tool ran"; rks says "no, that's out of scope" and you see the redirect.

You'll see both layers fire in Stages 4-6. The point of showing you now is so when they fire, they aren't a surprise — they're the system working as designed.

Does that make sense? Type **yes** to continue, or \`/rks-onboard --skip-tour\` to fast-forward to the wrap-up.`;

  if (!state.completedStages.includes("expectations")) {
    state.completedStages.push("expectations");
  }

  emit(projectRoot, "onboarder.stage.completed", {
    stage: "expectations",
    durationSeconds: Math.round((Date.now() - t0) / 1000),
  });

  return makePayload("expectations", state, display);
}

function handleStance(state, opts, projectRoot) {
  emit(projectRoot, "onboarder.stage.started", { stage: "stance" });
  const t0 = Date.now();

  const display = `rks is opinionated. There is one rule that drives most of the others: **every change is either a story or a framework update.**

A **story** is a unit of work in your project. It has a problem statement, a scope (which files the agent is allowed to touch), acceptance criteria, and tests. The Product Owner Governor (\`/po\`) writes them. The Build Governor (\`/build\`) implements them. The Ship Governor (\`/ship\`) commits and PRs them.

A **framework update** is a change to rks itself — the planner, the hooks, the prompts. You only do these if you're working on rks. For most child projects, all your work will be stories.

By writing a one-paragraph problem statement before each session, you get a plan you can review before it runs, a scope the hooks enforce while it runs, tests that prove it landed correctly, and a cost report that tells you what it actually cost. The discipline is the value. It's also why the agent doesn't freelance — it can't.

If you want to "just poke around" — that is what \`/po\` is for. Writing a quick story is cheap. The Product Owner Governor can take anywhere from a minute or two for something simple up to a longer run when it decomposes real complexity into multiple stories. We'll do exactly that in Stage 4.

**A note on where to start.** For most users, the expected first path is working within a child project — either an existing one you've attached to rks, or a fresh one you've just init'd. Framework-level changes (rks architecture, sub-agent design, MCP plugin development, how to introduce changes to the framework itself) are a different track. A future paper on "framework project onboarding" will cover that path in depth — for now, if you're working on rks itself, reach out or check the cross-references at the end of this document.

Type **ready** to move on to writing your first story.`;

  if (!state.completedStages.includes("stance")) {
    state.completedStages.push("stance");
  }

  emit(projectRoot, "onboarder.stage.completed", {
    stage: "stance",
    durationSeconds: Math.round((Date.now() - t0) / 1000),
  });

  return makePayload("stance", state, display);
}

const DEMO_PROBLEM_STATEMENT =
  "Add a Hello World React component to src/components/Hello.tsx";

function emitGovernorError(projectRoot, stage, governorResult, state) {
  emit(projectRoot, "onboarder.stage.failed", {
    stage,
    failureReason: "governor_error",
    governorError: governorResult.error || "unknown",
  });
  return makePayload(
    stage,
    state,
    `The Governor encountered an error during Stage ${stage}: ${governorResult.error || "unknown error"}\n\nCheck \`runs/\` in your project directory for the Governor session log, or refer to \`notes/how-to.child-project-kickoff.md\` for manual steps.`,
    { ok: false, error: governorResult.error || "governor_error" }
  );
}

function handleFirstStory(state, opts, projectRoot) {
  const responses = opts?.responses || {};
  const userInput = responses.userInput;
  const governorResult = responses.governorResult;

  if (governorResult) {
    if (governorResult.ok === false || governorResult.error) {
      return emitGovernorError(projectRoot, "first_story", governorResult, state);
    }

    emit(projectRoot, "onboarder.stage.started", { stage: "first_story" });
    const t0 = Date.now();

    const storyId = governorResult.storyId;
    if (!state.responses) state.responses = {};
    if (!state.responses.first_story) state.responses.first_story = {};
    state.responses.first_story.storyId = storyId;
    state.responses.first_story.isDemo = !!responses.isDemo;

    if (!state.completedStages.includes("first_story")) {
      state.completedStages.push("first_story");
    }

    emit(projectRoot, "onboarder.stage.completed", {
      stage: "first_story",
      storyId,
      durationSeconds: Math.round((Date.now() - t0) / 1000),
    });

    const display = `Story \`${storyId}\` has been written by the Product Owner Governor.

**A quick note on trust.** The hooks running during this session are open source at \`.routekit/hooks/\`. Every tool call the agent made is logged verbatim to \`runs/\` in your project directory. No data leaves your machine. The MCP server is open source under AGPL-3.0.

Type **build** to move to Stage 5 — the Build Governor will implement your story.`;

    return makePayload("first_story", state, display, { storyId });
  }

  const isDemo = userInput === "demo";
  const problemStatement = isDemo ? DEMO_PROBLEM_STATEMENT : (userInput || null);

  // Input received (a problem statement or `demo`): ACKNOWLEDGE it and dispatch the PO — do NOT
  // re-render the bare Stage 4 prompt with an empty nextAction (that read as "stuck" in UAT F2).
  // first_story is recorded on the follow-up call once the PO returns a governorResult (branch above).
  // (backlog.fix.onboarder-demo-stage-stuck)
  if (problemStatement) {
    const label = isDemo ? 'the "Hello Routekit!" demo story' : "your problem statement";
    const display = `Stage 4 of 7 — Your First Story.

Got it — dispatching the Product Owner Governor now to turn ${label} into a full story (acceptance criteria, scope, tests). This runs \`/po\`.

When it returns, type **build** to move to Stage 5.`;
    const result = makePayload("first_story", state, display);
    result.pendingDispatch = { type: "po", problemStatement, isDemo };
    result.nextAction = { type: "dispatch", governor: "po", problemStatement, isDemo };
    return result;
  }

  // No input yet — show the Stage 4 prompt. The demo option no longer assumes an init step the
  // tour never runs, and guards the framework-vs-project boundary (the demo writes real files).
  const display = `Stage 4 of 7 — Your First Story.

What problem do you want to solve in your project? Write one or two sentences. The Product Owner Governor will turn it into a full story with acceptance criteria, scope, and tests.

**Hello Routekit! option.** Want something concrete to start with? Type **demo** and we'll scaffold a small "Hello Routekit!" story so you can watch story-writing and decomposition end to end. Do this in your own project, not the rks framework repo — the demo writes real files. It's an option, not a requirement.

Type your problem statement (or **demo**) and we'll get the PO Governor running.`;

  return makePayload("first_story", state, display);
}

function handleFirstBuild(state, opts, projectRoot) {
  const responses = opts?.responses || {};
  const governorResult = responses.governorResult;
  const storyId = state.responses?.first_story?.storyId;

  if (!storyId) {
    return makePayload(
      "first_build",
      state,
      "Stage 4 result is missing — no story ID found in onboarder state. Please re-run Stage 4 first by calling `/rks-onboard --stage first_story`."
    );
  }

  if (governorResult) {
    if (governorResult.ok === false || governorResult.error) {
      return emitGovernorError(projectRoot, "first_build", governorResult, state);
    }

    emit(projectRoot, "onboarder.stage.started", { stage: "first_build" });
    const t0 = Date.now();

    const rawCost = governorResult.rawCost ?? null;
    const efficientCost = governorResult.efficientCost ?? null;
    const wasteRatio = governorResult.wasteRatio ?? null;
    const filesChanged = governorResult.filesChanged ?? null;
    const inputTokens = governorResult.inputTokens ?? null;
    const outputTokens = governorResult.outputTokens ?? null;
    const modelName = governorResult.modelName ?? null;

    if (!state.responses) state.responses = {};
    state.responses.first_build = { rawCost, efficientCost, wasteRatio, filesChanged, inputTokens, outputTokens, modelName };

    if (!state.completedStages.includes("first_build")) {
      state.completedStages.push("first_build");
    }

    emit(projectRoot, "onboarder.stage.completed", {
      stage: "first_build",
      storyId,
      rawCost,
      efficientCost,
      wasteRatio,
      durationSeconds: Math.round((Date.now() - t0) / 1000),
    });

    let costReport;
    if (rawCost != null) {
      costReport = `**Cost report:**
- Raw cost: $${rawCost.toFixed(4)}
- Efficient cost: $${efficientCost != null ? efficientCost.toFixed(4) : "n/a"}
- Waste ratio: ${wasteRatio != null ? (wasteRatio * 100).toFixed(1) + "%" : "n/a"}

The raw cost is what you'd pay with no caching. The efficient cost is after prompt caching. The waste ratio shows how much of the raw spend was eliminated.`;
    } else {
      costReport = `Cost reporting is not yet available in this version of rks. Check \`runs/\` in your project directory for the raw Governor log.`;
    }

    const display = `Build complete for \`${storyId}\`.

${costReport}

Type **ship** to move to Stage 6 — the Ship Governor will open a PR.`;

    return makePayload("first_build", state, display, { storyId, rawCost, efficientCost, wasteRatio });
  }

  const display = `Stage 5 of 7 — First Build.

The Build Governor will implement \`${storyId}\`. Here is what happens:

1. **Plan** — The planner generates a step-by-step plan scoped to the story's target files.
2. **Review** — You see the plan before it runs.
3. **Exec** — The executor applies the plan file by file, with hooks enforcing scope.
4. **Test** — The test runner verifies acceptance criteria.
5. **Cost** — A cost report shows what this build actually cost.

Type **run** to launch the Build Governor, or \`/build ${storyId}\` directly.`;

  const result = makePayload("first_build", state, display);
  result.pendingDispatch = { type: "build", storyId };
  return result;
}

function handleFirstShip(state, opts, projectRoot) {
  const responses = opts?.responses || {};
  const governorResult = responses.governorResult;
  const storyId = state.responses?.first_story?.storyId || null;

  if (governorResult) {
    if (governorResult.ok === false || governorResult.error) {
      return emitGovernorError(projectRoot, "first_ship", governorResult, state);
    }

    emit(projectRoot, "onboarder.stage.started", { stage: "first_ship" });
    const t0 = Date.now();

    const prUrl = governorResult.prUrl ?? null;
    const prState = governorResult.prState ?? null;
    const commitSha = governorResult.commitSha ?? null;
    const integrationBranch = governorResult.integrationBranch ?? null;

    if (!state.responses) state.responses = {};
    state.responses.first_ship = { prUrl, prState, commitSha, integrationBranch };

    if (!state.completedStages.includes("first_ship")) {
      state.completedStages.push("first_ship");
    }

    emit(projectRoot, "onboarder.stage.completed", {
      stage: "first_ship",
      storyId,
      prUrl,
      prState,
      durationSeconds: Math.round((Date.now() - t0) / 1000),
    });

    let shipRef;
    if (prUrl) {
      shipRef = `**PR:** ${prUrl} (${prState || "open"})`;
    } else if (commitSha) {
      shipRef = `**Commit:** \`${commitSha}\` → \`${integrationBranch}\``;
    } else {
      shipRef = "Ship complete.";
    }

    const display = `Shipped. ${shipRef}

Three things to look at:
1. **The diff** — the actual changes the Build Governor applied.
2. **The cost report** — in the PR body, the full cost breakdown.
3. **CI status** — your pipeline should be running against these changes.

Type **next** to move to Stage 7 — we'll wrap up and show you where to go from here.`;

    return makePayload("first_ship", state, display, { storyId, prUrl, prState, commitSha, integrationBranch });
  }

  const display = `Stage 6 of 7 — First Ship.

The Ship Governor will commit the changes, open a PR, and attach the cost report to the PR body.

Type **ship** to run \`/ship\` now.`;

  const result = makePayload("first_ship", state, display);
  result.pendingDispatch = { type: "ship", storyId };
  return result;
}

function handleNextSteps(state, _opts, projectRoot) {
  emit(projectRoot, "onboarder.stage.started", { stage: "next_steps" });
  const t0 = Date.now();

  const storyId = state.responses?.first_story?.storyId || null;
  const buildData = state.responses?.first_build || null;
  const shipData = state.responses?.first_ship || null;
  const totalDurationSeconds = state.startedAt
    ? Math.round((Date.now() - state.startedAt) / 1000)
    : 0;

  const costLine = buildCostSummary(buildData);
  const prRef = shipData?.prUrl || "n/a";

  const summaryPanel = `**Session summary:**
  Story shipped: ${storyId || "none (stages skipped)"}
  Build cost:    ${costLine}
  PR:            ${prRef}
  Duration:      ${totalDurationSeconds}s`;

  const display = `Stage 7 of 7 — Where to next.

${summaryPanel}

You've seen rks end-to-end. Here's the quick reference:

**Slash commands:**
- \`/po "describe a problem"\` — write a story (Product Owner Governor)
- \`/build <problemId>\` — build an existing story (Build Governor)
- \`/ship\` — commit and open a PR (Ship Governor)
- \`/research "question or task"\` — research, design, or document something
- \`/release patch|minor|major\` — release staging to main with version bump

You can also just describe what you want in chat and the Dispatcher will route you to the right skill.

**Papers worth reading (in priority order):**
1. \`notes/research.2026.04.30.rks-onboarder-design.md\` — onboarder design and rationale
2. \`notes/how-to.agent-operations.3-build.md\` — Build Governor reference
3. \`notes/how-to.child-project-kickoff.md\` — child project setup checklist

**Bookmark:** \`notes/how-to.child-project-kickoff.md\` covers the manual setup steps if you ever need to re-configure a child project from scratch.

**0.x maturity note.** rks is pre-1.0. Behavior can change between releases. Pin to a specific tag in child projects: \`"@routekit/mcp-rks": "github:ux287/routekit-shell#v0.x.y"\`. Check releases at https://github.com/ux287/routekit-shell/releases.

**UX287** — Feedback, questions, and reports: open an issue or start a discussion at https://github.com/ux287/routekit-shell.`;

  // Write completedAt to project.json; preserve completedVersion if already set (e.g. "skipped-as-power-user")
  const proj = readProjectJson(projectRoot);
  proj.onboarder = {
    ...(proj.onboarder || {}),
    completedAt: Date.now(),
    completedVersion: proj.onboarder?.completedVersion || "1.0",
  };
  writeProjectJson(projectRoot, proj);

  if (!state.completedStages.includes("next_steps")) {
    state.completedStages.push("next_steps");
  }
  state.completedAt = Date.now();

  const storiesShipped =
    state.completedStages.includes("first_ship") && (shipData?.prUrl || shipData?.commitSha) ? 1 : 0;
  const stagesSkipped = STAGES.filter(
    (s) => state.completedStages.includes(s) && !state.responses?.[s] && s !== "next_steps"
  );
  const totalTokens = buildData?.inputTokens != null
    ? buildData.inputTokens + (buildData.outputTokens || 0)
    : 0;

  emit(projectRoot, "onboarder.stage.completed", {
    stage: "next_steps",
    durationSeconds: Math.round((Date.now() - t0) / 1000),
  });

  emit(projectRoot, "onboarder.completed", {
    totalDurationSeconds,
    totalTokens,
    storiesShipped,
    stagesSkipped,
  });

  return makePayload("next_steps", state, display);
}

const HANDLERS = {
  welcome: handleWelcome,
  expectations: handleExpectations,
  stance: handleStance,
  first_story: handleFirstStory,
  first_build: handleFirstBuild,
  first_ship: handleFirstShip,
  next_steps: handleNextSteps,
};

// ─── Entry point ──────────────────────────────────────────────────────────────

function selectStage(state, explicitStage) {
  if (explicitStage) return explicitStage;
  const completed = new Set(state.completedStages || []);
  for (const stage of STAGES) {
    if (!completed.has(stage)) return stage;
  }
  return "next_steps";
}

export async function runOnboarder({
  projectId,
  projectRoot,
  stage,
  responses,
  skipTour,
  skipStage,
  bounce,
  resume,
  reset,
} = {}) {
  const root = projectRoot || process.cwd();
  let state = getOnboarderState(root);
  if (projectId) state.projectId = projectId;

  // Abandoned inference: emit once when a prior session is stale (> 24h) and never completed
  const TWENTY_FOUR_HOURS = 24 * 60 * 60 * 1000;
  if (
    state.startedAt &&
    !state.completedAt &&
    !state.abandonedEmitted &&
    Date.now() - state.lastTouchedAt > TWENTY_FOUR_HOURS
  ) {
    emit(root, "onboarder.abandoned", {
      stuckAt: state.currentStage,
      lastTouchedAt: state.lastTouchedAt,
    });
    state.abandonedEmitted = true;
    saveOnboarderState(root, state);
  }

  if (reset) {
    const now = Date.now();
    state = {
      version: 1,
      startedAt: now,
      lastTouchedAt: now,
      completedStages: [],
      currentStage: "welcome",
      projectId: projectId || state.projectId,
    };
    saveOnboarderState(root, state);
  }

  // skipTour: mark all stages except next_steps as skipped, jump to next_steps
  if (skipTour) {
    const skippable = STAGES.filter(s => s !== "next_steps");
    for (const s of skippable) {
      if (!state.completedStages.includes(s)) {
        emit(root, "onboarder.stage.skipped", { stage: s, reason: "dismissed" });
      }
    }
    state.completedStages = skippable;
    state.currentStage = "next_steps";
    const proj = readProjectJson(root);
    proj.onboarder = {
      ...(proj.onboarder || {}),
      completedAt: Date.now(),
      completedVersion: "skipped-as-power-user",
    };
    writeProjectJson(root, proj);
    const saved = saveOnboarderState(root, state);
    const result = handleNextSteps(saved, {}, root);
    result.state = saved;
    return result;
  }

  const targetStage = selectStage(state, stage);

  // skipStage: skip current stage, advance to next
  if (skipStage) {
    emit(root, "onboarder.stage.skipped", { stage: targetStage, reason: "user-skip" });
    if (!state.completedStages.includes(targetStage)) {
      state.completedStages.push(targetStage);
    }
    state.currentStage = targetStage;
    const saved = saveOnboarderState(root, state);
    const nextStage = selectStage(saved, null);
    const handler = HANDLERS[nextStage];
    if (!handler) return { ok: false, error: `Unknown stage: ${nextStage}` };
    const result = handler(saved, { responses, bounce }, root);
    saved.currentStage = nextStage;
    result.state = saveOnboarderState(root, saved);
    return result;
  }

  const handler = HANDLERS[targetStage];
  if (!handler) {
    return { ok: false, error: `Unknown stage: ${targetStage}` };
  }

  const result = handler(state, { responses, bounce }, root);
  state.currentStage = targetStage;
  const saved = saveOnboarderState(root, state);
  result.state = saved;
  return result;
}
