/**
 * Tests for templates/base/CLAUDE.md — the source for a fresh child's CLAUDE.md
 * (generated by ensureClaudeMd in packages/cli/src/project/bootstrap.mjs via
 * __PROJECT_ID__ substitution).
 *
 * Story: backlog.feat.child-claudemd-route-build-through-skills (UAT finding F7)
 *
 * The template must route build/PO/QA/ARCH through the shipped skills (not inline
 * hand-rolled Governor prompts that skip QA/ARCH/analyze-recovery/plan_ready), keep
 * the inline onboarding bootstrap (NOT /onboard — that file is not copied to
 * children), and NOT copy core-only governance sections.
 *
 * ensureClaudeMd is private (only attachProject/bootstrapProject are exported), so
 * the generated-child assertions mirror its exact substitution with a readFileSync
 * + replace, avoiding git/subprocess fixtures.
 */
import { describe, it, expect } from "vitest";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const templatePath = path.resolve(__dirname, "../../templates/base/CLAUDE.md");
const template = fs.readFileSync(templatePath, "utf8");

describe("templates/base/CLAUDE.md — routes build through skills (F7)", () => {
  describe("skills routing", () => {
    it("references only the provisioned directory skills", () => {
      for (const skill of ["/research", "/pipeline", "/build", "/qa", "/arch", "/ship", "/telemetry"]) {
        expect(template).toContain(skill);
      }
    });

    it("does NOT reference /onboard or /welcome (they are files, not copied to children)", () => {
      expect(template).not.toContain("/onboard");
      expect(template).not.toContain("/welcome");
    });

    it("carries the behavioral instruction (no direct MCP workflow tools; skills launch Governors)", () => {
      expect(template).toContain("MUST NOT call MCP workflow tools directly");
      expect(template).toMatch(/Skills launch Governors/);
      expect(template).toMatch(/you launch the skill/);
    });
  });

  describe("no hand-rolled inline Build prompt (the F7 regression)", () => {
    it("has no '### Governor prompt (build)' heading", () => {
      expect(template).not.toMatch(/Governor prompt \(build\)/);
    });

    it("does not embed an inline refine -> plan -> exec build chain as the build path", () => {
      // The old template inlined an rks_refine/rks_plan/rks_exec chain in a code block.
      expect(template).not.toMatch(/rks_plan_review/);
      expect(template).not.toMatch(/autoShip:\s*true/);
    });

    it("has a single coherent build section (not the two duplicated headings)", () => {
      expect(template).not.toContain("## Build — from task description");
      expect(template).not.toContain("## Build — story-based");
    });
  });

  describe("onboarding stays inline (NOT /onboard)", () => {
    it("retains the inline rag_init -> rag_embed -> preflight bootstrap with __PROJECT_ID__", () => {
      expect(template).toMatch(/rks_rag_init\(\{ projectId: '__PROJECT_ID__' \}\)/);
      expect(template).toMatch(/rks_rag_embed\(\{ projectId: '__PROJECT_ID__' \}\)/);
      expect(template).toMatch(/rks_preflight\(\{ projectId: '__PROJECT_ID__' \}\)/);
    });
  });

  describe("preserved sections", () => {
    it("preserves an On Governor return section", () => {
      expect(template).toContain("## On Governor return");
    });

    it("has a Behavioral Rules / grounding block", () => {
      expect(template).toContain("## Behavioral Rules");
    });

    it("keeps telemetry reachable (via /telemetry or inline rks_telemetry_*)", () => {
      expect(template.includes("/telemetry") || template.includes("rks_telemetry_report")).toBe(true);
    });
  });

  describe("does not copy core-only governance sections", () => {
    it("omits core-only machinery", () => {
      for (const section of [
        "Build Path Analysis",
        "offRail",
        "Skill Verbosity",
        "Test Execution",
        "Singleton Rule",
        "Dispatcher Read Boundary Rule",
      ]) {
        expect(template).not.toContain(section);
      }
    });

    it("does not leak the parent projectId routekit-shell-core", () => {
      expect(template).not.toContain("routekit-shell-core");
    });

    it("retains the __PROJECT_ID__ placeholder on the projectId line", () => {
      expect(template).toMatch(/\*\*projectId\*\*:\s*`"__PROJECT_ID__"`/);
    });
  });

  describe("generated child output (mirrors ensureClaudeMd substitution)", () => {
    const generate = (id) => template.replace(/__PROJECT_ID__/g, id);

    it("substitutes the real projectId with no literal placeholder left", () => {
      const out = generate("my-child-app");
      expect(out).toContain('"my-child-app"');
      expect(out).not.toContain("__PROJECT_ID__");
    });

    it("generated child does not leak a parent projectId", () => {
      const out = generate("my-child-app");
      expect(out).not.toContain("routekit-shell-core");
      expect(out).not.toContain("routekit-shell-release");
    });
  });
});
