/**
 * Witness for backlog.fix.build-prompt-plan-gate-contradiction.
 *
 * THE DEFECT: two correct-in-isolation shipped stories contradicted each other, and the Build
 * Governor was the casualty.
 *
 *   - `governor-build.md` step 3.5 excluded `no_search_pattern_for_modify` from its STOP set,
 *     treating it as a pass-through. That came from backlog.z_implemented.feat.build-governor-
 *     plan-ready-passthrough, whose stated premise was "@@SEARCH blocks are generated by the
 *     planner and are not required pre-plan".
 *   - backlog.fix.rks-plan.not-ready-short-circuit then falsified that premise: the pre-spawn
 *     readiness gate runs `runPlanReadyTool` BEFORE spawning a plan worker and returns
 *     `not_ready` on ANY blocking issue, without discriminating by check name.
 *
 * So Build read the issue, correctly concluded its prompt said proceed, called the plan step, and
 * received a bare `not_ready` naming nothing actionable. Observed live on
 * backlog.fix.exhaustive-search-dotdir-silent-zero. Child projects run on-rail, so this blocked
 * them on the first story that had an `op: edit` target without an anchor.
 *
 * TEST APPROACH — region extracted between BOTH bounding markers, never a fixed-size
 * `slice(idx, idx + N)` window. This repo has a standing problem with stale positions, and a
 * fixed window silently stops covering the thing it was written to cover as soon as text is
 * inserted above it.
 */
import { describe, it, expect } from "vitest";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "../..");

const PROMPT = fs.readFileSync(
  path.join(REPO_ROOT, ".rks/prompts/governor-build.md"),
  "utf8",
);

/** Step 3.5, bounded on BOTH sides by durable markers. */
function step35Region() {
  const start = PROMPT.indexOf("3.5. mcp__rks__rks_plan_ready");
  const end = PROMPT.indexOf("\n4. mcp__rks__rks_plan(", start);
  expect(start, "step 3.5 marker not found — prompt structure changed").toBeGreaterThan(-1);
  expect(end, "step 4 marker not found — prompt structure changed").toBeGreaterThan(start);
  return PROMPT.slice(start, end);
}

describe("step 3.5 no longer passes the blocking issue through", () => {
  it("THE FIX: the exclusion clause is gone", () => {
    // The exact shape of the defect: an `other than …` clause naming the issue, which made it a
    // pass-through. `[^\n]*` deliberately cannot cross a line boundary, so this stays precise
    // even though both strings still appear in the region on separate lines.
    expect(step35Region()).not.toMatch(/other than[^\n]*no_search_pattern_for_modify/);
  });

  it("the issue is named by an ACTIVE branch, not merely absent", () => {
    // Deleting the mention entirely would also satisfy the assertion above while leaving Build
    // with no instruction at all for this issue. The branch has to exist.
    const region = step35Region();
    expect(region).toContain("no_search_pattern_for_modify");
    expect(region).toMatch(/add_search_pattern/);
  });

  it("the branch remediates, re-verifies, and only then proceeds", () => {
    const region = step35Region();
    expect(region).toMatch(/rks_refine_apply/);
    // Re-running the readiness check after remediating is the load-bearing half: applying a
    // refinement is not evidence the block cleared.
    expect(region).toMatch(/re-run rks_plan_ready/i);
  });

  it("it STOPs with plan_ready_blocked when remediation fails", () => {
    const region = step35Region();
    expect(region).toContain("plan_ready_blocked");
    // The failure has to be actionable — a bare `not_ready` naming nothing is the original
    // complaint. The summary must name the files lacking anchors.
    expect(region).toMatch(/@@SEARCH anchors/);
  });

  it("it handles the manual:true fallback rather than dead-ending", () => {
    expect(step35Region()).toMatch(/manual: true/);
  });
});

describe("the neighbouring branches are untouched", () => {
  it("multi_file_blocked still remediates and proceeds", () => {
    const region = step35Region();
    expect(region).toContain("multi_file_blocked");
    expect(region).toContain("acknowledge_multi_file");
  });

  it("the ok:true fast path still proceeds directly", () => {
    expect(step35Region()).toMatch(/If ok: true[^\n]*proceed to step 4/);
  });

  it("any OTHER blocking issue still STOPs", () => {
    // The generic catch-all must survive. Removing the exclusion must not accidentally remove
    // the clause it was attached to.
    expect(step35Region()).toMatch(/other than `multi_file_blocked`/);
  });
});

describe("the insertion respects the constraints other witnesses depend on", () => {
  // tests/unit/governor-build-prompt.test.mjs walks these markers with monotonically increasing
  // indexOf. Text inserted at 3.5 that began a line with a numbered step prefix, or that repeated
  // a later marker literal, would reorder them and red that file.
  it("step markers remain in monotonically increasing order", () => {
    const markers = [
      "0. mcp__rks__rks_governor_init",
      "1. mcp__rks__rks_refine(",
      "3.5. mcp__rks__rks_plan_ready",
      "\n4. mcp__rks__rks_plan(",
      "5. POLL rks_plan_review",
    ];
    let prev = -1;
    for (const marker of markers) {
      const idx = PROMPT.indexOf(marker);
      expect(idx, `marker not found: ${marker}`).toBeGreaterThan(-1);
      expect(idx, `marker out of order: ${marker}`).toBeGreaterThan(prev);
      prev = idx;
    }
  });

  it("the inserted text does not contain the step-4 marker literal", () => {
    // A second occurrence would make `indexOf("\n4. mcp__rks__rks_plan(")` resolve inside step
    // 3.5, collapsing the region this file extracts and silently truncating every assertion above.
    const occurrences = PROMPT.split("\n4. mcp__rks__rks_plan(").length - 1;
    expect(occurrences).toBe(1);
  });

  it("no line inside step 3.5 begins with a numbered step prefix", () => {
    // The region's own header IS "3.5. …" and legitimately carries the prefix — it is the marker
    // the ordering walk above locates. Every line AFTER it must not, or the walk gains a spurious
    // waypoint between 3.5 and 4.
    const [header, ...body] = step35Region().split("\n");
    expect(header).toMatch(/^3\.5\.\s/);
    for (const line of body) {
      expect(line, `line begins a numbered step: ${line}`).not.toMatch(/^\d+(\.\d+)?\.\s/);
    }
  });

  it("build-retry-via-refine's fromIndex anchor still resolves after step 6a", () => {
    // That witness does indexOf('rks_refine_apply', indexOf('step 6a')). The new occurrence at
    // 3.5 sits BEFORE step 6a, so the fromIndex makes it unreachable — but only while step 6a
    // still exists and still has an rks_refine_apply after it. Pinned so a later edit can't
    // quietly invalidate the reasoning that cleared this story.
    const step6a = PROMPT.indexOf("step 6a");
    expect(step6a, "step 6a marker not found").toBeGreaterThan(-1);
    expect(PROMPT.indexOf("rks_refine_apply", step6a)).toBeGreaterThan(step6a);
  });
});
